### ISSUE TITLE
GUI : copy / paste function does not work

### ISSUE THREAD

**Issue by guilpier-code** [AntaresSimulatorTeam/Antares_Simulator#734]
As long as we want to copy / paste an area or any selection, the GUI gets stuck and does not gives back control to the user.
Here is a snapshot of the GUI when it gets stuck.
![getting-stuck-on-copy-pate](https://user-images.githubusercontent.com/62292552/176180646-2d81e0bd-8ddc-485a-881c-28dd79ef4573.PNG)

See the following attached study for bug reproduction.
[BindConst--infinity-on-thCluster.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/9001085/BindConst--infinity-on-thCluster.zip)

**Comment by flomnes** [comment]
Freeze does not occur when copy/pasting only one area. It does when copy/pasting multiple areas/links.

**Comment by flomnes** [comment]
The freeze seems to be related to the event queue
```
#7  0x0000555555ab304c in Antares::Private::Dispatcher::JobShowModalThenDestroy::onExecute (this=0x55555a0a3c00) at /home/omnesflo/Antares_Simulator/src/ui/common/dispatcher/gui.cpp:117
117	        pForm->ShowModal();
(gdb) bt
#0  0x00007ffff4457aff in __GI___poll (fds=0x55555754f4b0, nfds=3, timeout=197) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff37a736e in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff37a76f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff3ddf37d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff7bbd575 in wxGUIEventLoop::DoRun() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#5  0x00007ffff7723d41 in wxEventLoopBase::Run() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#6  0x00007ffff7c282f2 in wxDialog::ShowModal() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#7  0x0000555555ab304c in Antares::Private::Dispatcher::JobShowModalThenDestroy::onExecute() (this=0x55555a0a3c00) at /home/omnesflo/Antares_Simulator/src/ui/common/dispatcher/gui.cpp:117
#8  0x0000555555c2af3a in Yuni::Job::IJob::execute(Yuni::Thread::IThread*) (this=0x55555a0a3c00, t=0x0) at /home/omnesflo/Antares_Simulator/src/ext/yuni/src/yuni/job/job.cpp:64
#9  0x0000555555ab19ee in Antares::Dispatcher::Internal::ExecuteQueueDispatcher() () at /home/omnesflo/Antares_Simulator/src/ui/common/dispatcher/action.cpp:200
#10 0x00005555557fe393 in Antares::Forms::ApplWnd::evtOnExecuteQueueEvent(wxCommandEvent&) (this=0x5555573c4e00) at /home/omnesflo/Antares_Simulator/src/ui/simulator/application/main/main.cpp:1081
#11 0x00007ffff786f641 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#12 0x00007ffff786f743 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#13 0x00007ffff786faa0 in wxEvtHandler::TryHereOnly(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#14 0x00007ffff786f903 in wxEvtHandler::DoTryChain(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#15 0x00007ffff786fbd1 in wxEvtHandler::ProcessEvent(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#16 0x00007ffff78705b2 in wxEvtHandler::ProcessPendingEvents() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#17 0x00007ffff76e98ff in wxAppConsoleBase::ProcessPendingEvents() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#18 0x00007ffff7b9f699 in wxApp::DoIdle() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#19 0x00007ffff7b9f7a7 in  () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#20 0x00007ffff37a704e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff37a7400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff37a76f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff3ddf37d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff7bbd575 in wxGUIEventLoop::DoRun() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#25 0x00007ffff7723d41 in wxEventLoopBase::Run() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#26 0x00007ffff76eb3da in wxAppConsoleBase::MainLoop() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#27 0x00007ffff777773d in wxEntry(int&, wchar_t**) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#28 0x000055555584bf45 in main(int, char**) (argc=1, argv=0x7fffffffdce8) at /home/omnesflo/Antares_Simulator/src/ui/simulator/main.cpp:108
```

**Comment by flomnes** [comment]
Also : segfault

**Comment by flomnes** [comment]
Looking closely at the stack trace, there seems to be some repetition
```gdb
#0  0x00007ffff6b9caff in __GI___poll (fds=0x555557f04a20, nfds=3, timeout=7148) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff5eec36e in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5eec6f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff652437d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff7bbd575 in wxGUIEventLoop::DoRun() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#5  0x00007ffff7723d41 in wxEventLoopBase::Run() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#6  0x00007ffff7c282f2 in wxDialog::ShowModal() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#7  0x0000555555a45f56 in Antares::Private::Dispatcher::JobShowModalThenDestroy::onExecute() (this=0x55555a794fe0) at /home/omnesflo/Antares_Simulator/src/ui/common/dispatcher/gui.cpp:117
#8  0x0000555555bbe710 in Yuni::Job::IJob::execute(Yuni::Thread::IThread*) (this=0x55555a794fe0, t=0x0) at /home/omnesflo/Antares_Simulator/src/ext/yuni/src/yuni/job/job.cpp:64
#9  0x0000555555a448f8 in Antares::Dispatcher::Internal::ExecuteQueueDispatcher() () at /home/omnesflo/Antares_Simulator/src/ui/common/dispatcher/action.cpp:200
#10 0x0000555555791013 in Antares::Forms::ApplWnd::evtOnExecuteQueueEvent(wxCommandEvent&) (this=0x555557d94a00) at /home/omnesflo/Antares_Simulator/src/ui/simulator/application/main/main.cpp:1081
#11 0x00007ffff786f641 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#12 0x00007ffff786f743 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#13 0x00007ffff786faa0 in wxEvtHandler::TryHereOnly(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#14 0x00007ffff786f903 in wxEvtHandler::DoTryChain(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#15 0x00007ffff786fbd1 in wxEvtHandler::ProcessEvent(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#16 0x00007ffff78705b2 in wxEvtHandler::ProcessPendingEvents() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#17 0x00007ffff76e98ff in wxAppConsoleBase::ProcessPendingEvents() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#18 0x00007ffff7b9f699 in wxApp::DoIdle() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#19 0x00007ffff7b9f7a7 in  () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#20 0x00007ffff5eec04e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff5eec400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff5eec6f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff652437d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff7bbd575 in wxGUIEventLoop::DoRun() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#25 0x00007ffff7723d41 in wxEventLoopBase::Run() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#26 0x00007ffff7c282f2 in wxDialog::ShowModal() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#27 0x0000555555a45f56 in Antares::Private::Dispatcher::JobShowModalThenDestroy::onExecute() (this=0x555559ebf700) at /home/omnesflo/Antares_Simulator/src/ui/common/dispatcher/gui.cpp:117
#28 0x0000555555bbe710 in Yuni::Job::IJob::execute(Yuni::Thread::IThread*) (this=0x555559ebf700, t=0x0) at /home/omnesflo/Antares_Simulator/src/ext/yuni/src/yuni/job/job.cpp:64
#29 0x0000555555a448f8 in Antares::Dispatcher::Internal::ExecuteQueueDispatcher() () at /home/omnesflo/Antares_Simulator/src/ui/common/dispatcher/action.cpp:200
#30 0x0000555555791013 in Antares::Forms::ApplWnd::evtOnExecuteQueueEvent(wxCommandEvent&) (this=0x555557d94a00) at /home/omnesflo/Antares_Simulator/src/ui/simulator/application/main/main.cpp:1081
#31 0x00007ffff786f641 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#32 0x00007ffff786f743 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#33 0x00007ffff786faa0 in wxEvtHandler::TryHereOnly(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#34 0x00007ffff786f903 in wxEvtHandler::DoTryChain(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#35 0x00007ffff786fbd1 in wxEvtHandler::ProcessEvent(wxEvent&) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#36 0x00007ffff78705b2 in wxEvtHandler::ProcessPendingEvents() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#37 0x00007ffff76e98ff in wxAppConsoleBase::ProcessPendingEvents() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#38 0x00007ffff7b9f699 in wxApp::DoIdle() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#39 0x00007ffff7b9f7a7 in  () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#40 0x00007ffff5eec04e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff5eec400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007ffff5eec6f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007ffff652437d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#44 0x00007ffff7bbd575 in wxGUIEventLoop::DoRun() () at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#45 0x00007ffff7723d41 in wxEventLoopBase::Run() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#46 0x00007ffff76eb3da in wxAppConsoleBase::MainLoop() () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#47 0x00007ffff777773d in wxEntry(int&, wchar_t**) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#48 0x00005555557debc5 in main(int, char**) (argc=1, argv=0x7fffffffdd28) at /home/omnesflo/Antares_Simulator/src/ui/simulator/main.cpp:108
```
It seems that another thread is launched by the event dispatch queue. I found a similar [issue](https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/586) (Linux only) for "Save As...". The event queue was never depleted because jobs were created endlessly.

**Comment by flomnes** [comment]
Also
```
[Wed Jul 13 09:04:53 2022][antares][error] The area named 'area-5' has a link to itself
Erreur de segmentation (core dumped)
```
This feature is broken beyond repair.
