### ISSUE TITLE
Export crashes when many BCs are present

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#912]
v8.3.2

```
#4  0x0000555555646f7b in Antares::Solver::Variable::R::AllYears::Average<Antares::Solver::Variable::R::AllYears::StdDeviation<Antares::Solver::Variable::R::AllYears::Min<Antares::Solver::Variable::R::AllYears::Max<Antares::Solver::Variable::Empty> >, 255>, 255>::InternalExportValues<8785u, Antares::Solver::Variable::Economy::VCardBindingConstMarginCost, 1> (
    this=0x5556c584fb30, report=..., array=0x5556c6b22a10) at /home/omnesflo/Projects/Antares_Simulator/src/solver/main/../simulation/../variable/storage/average.h:203
203	        assert(report.data.columnIndex < report.maxVariables && "Column index out of bounds");
(gdb) p report.data.columnIndex 
$1 = 144
(gdb) p report.data.maxVariables
There is no member or method named maxVariables.
(gdb) p report.maxVariables
$2 = 144
...
#9  0x0000555555624488 in Antares::Solver::Variable::BindingConstraints<Antares::Solver::Variable::Economy::BindingConstMarginCost<Antares::Solver::Variable::Container::EndOfList> >::buildSurveyReport (this=0x7fffffffca70, results=..., dataLevel=32, fileLevel=128, precision=1)
    at /home/omnesflo/Projects/Antares_Simulator/src/solver/main/../simulation/../variable/economy/../bindConstraints.hxx:48
48	        bc.buildSurveyReport(results, dataLevel, fileLevel, precision);
```

**Comment by flomnes** [comment]
The study has many = BC, and a few < or > BCs. There might be a problem with indices (global vs inequality)

**Comment by guilpier-code** [comment]
Please supply a study that crashes
